name: Artemis
url: https://github.com/Dreyer/hexo-theme-artemis

menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/Dreyer
  RSS: /atom.xml

favicon: /favicon.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
mathjax: false
google_analytics:

# Copyright Infomation
copyright:
  since: 2019
  name: Jakub Szczerbiński
  url: ksi.cs.uni.wroc.pl
